name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git
        pip3 install buildozer

    - name: Set up buildozer
      run: |
        sudo apt install -y libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev
        buildozer init || true
        sed -i 's/^requirements = .*/requirements = python3,kivy,requests/' buildozer.spec
        sed -i 's/^package.domain = .*/package.domain = org.hamkay.quotespark/' buildozer.spec
        sed -i 's/^title = .*/title = QuoteSpark/' buildozer.spec

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: quotespark-apk
        path: bin/*.apk
