name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git wget \
          autoconf automake libtool gettext libltdl-dev
        pip3 install --upgrade pip
        pip3 install buildozer cython


    - name: Download Android SDK Command Line Tools
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        cd $HOME/.buildozer/android/platform/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O sdk-tools.zip
        unzip sdk-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest

    - name: Install Android SDK Packages and Accept Licenses
      run: |
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;23.1.7779620"

    - name: Configure buildozer.spec
      run: |
        buildozer init || true
        sed -i 's/^requirements = .*/requirements = python3,kivy,requests/' buildozer.spec
        sed -i 's/^package.domain = .*/package.domain = org.hamkay.quotespark/' buildozer.spec
        sed -i 's/^title = .*/title = QuoteSpark/' buildozer.spec
        echo "android.sdk_path = $HOME/.buildozer/android/platform/android-sdk" >> buildozer.spec
        echo "android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r23b" >> buildozer.spec
    
    - name: Patch sdkmanager path for Buildozer
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
        ln -s $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: quotespark-apk
        path: bin/*.apk
